spring:
  application:
    name: store-login-register
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/wugustore?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/