spring:
  application:
    name: store-zuul

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/

zuul:
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods
  routes:
    store-main:
      path: /main/**
      serviceId: store-main
    store-detail:
      path: /detail/**
      serviceId: store-detail
    store-order-pay:
      path: /order/**
      serviceId: store-order-pay
    store-shoppingcart:
      path: /shoppingCart/**
      serviceId: store-shoppingCart
    store-login-register:
      path: /loginRegister/**
      serviceId: store-login-register