spring:
  application:
    name: store-zuul

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/

ribbon:
  connectTimeout: 2000
  readTimeout: 5000

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  sensitive-headers:

  routes:
    api-wallet:
      path: /api/**
      serviceId: store-main