spring:
  application:
    name: store-session
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

server:
  port: 8280

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/